// src/js/components-react/subscriptions/List.jsx
import { __ } from '@wordpress/i18n';
import { useState, useEffect, useMemo } from '@wordpress/element';
import { useSelect, useDispatch } from '@wordpress/data';
import { Spinner } from '@wordpress/components';
import SubscriptionBox from './SubscriptionBox';
import Empty from './Empty';
import Pagination from './Pagination';
import ListHeader from './ListHeader';

export default function List() {
    const [paginationKey, setPaginationKey] = useState(0);

    const {
        subscriptionList,
        isSubscriptionLoading,
        currentSubscriptionStatus,
        counts,
        currentPage,
    } = useSelect((select) => {
        const store = select('wpuf/subscriptions');
        return {
            subscriptionList: store.getItems(),
            isSubscriptionLoading: store.isLoading(),
            currentSubscriptionStatus: store.getCurrentStatus(),
            counts: store.getCounts(),
            currentPage: store.getCurrentPage(),
        };
    }, []);

    const { setSubscriptionsByStatus, setCurrentPage } = useDispatch('wpuf/subscriptions');

    const wpufSubscriptions = window.wpufSubscriptions || {};
    const perPage = parseInt(wpufSubscriptions.perPage || 10);

    const count = useMemo(() => {
        if (!counts || !currentSubscriptionStatus) {
            return 0;
        }
        return counts[currentSubscriptionStatus] || counts.all || 0;
    }, [counts, currentSubscriptionStatus]);

    const totalPages = useMemo(() => {
        return Math.ceil(count / perPage);
    }, [count, perPage]);

    const maxVisibleButtons = 3;

    const emptyMessages = {
        all: __(
            "Powerful Subscription Features for Monetizing Your Content. Unlock a World of Possibilities with WPUF's Subscription Features – From Charging Users for Posting to Exclusive Content Access.",
            'wp-user-frontend'
        ),
        publish: __(
            "Ops! It looks like you haven't published any subscriptions yet. To create a new subscription and start monetizing your content, click the 'Add Subscription' button above.",
            'wp-user-frontend'
        ),
        draft: __("Ops! It looks like you haven't saved any subscriptions as drafts yet.", 'wp-user-frontend'),
        trash: __('Your trash is empty! If you delete a subscription, it will be moved here.', 'wp-user-frontend'),
    };

    const headerMessage = {
        all: __('Manage and monitor all your subscriptions. Edit details or create new ones as needed.', 'wp-user-frontend'),
        publish: __('Oversee all active subscriptions currently available for users.', 'wp-user-frontend'),
        draft: __('Handle subscriptions that are saved as drafts but not yet published.', 'wp-user-frontend'),
        trash: __('Review deleted subscriptions. Restore or permanently delete them as required.', 'wp-user-frontend'),
    };

    // Update count when status changes
    useEffect(() => {
        setPaginationKey((prev) => prev + 1);
    }, [counts, currentSubscriptionStatus]);

    const changePageTo = (page) => {
        const offset = (page - 1) * perPage;
        setSubscriptionsByStatus(currentSubscriptionStatus, offset);
        setCurrentPage(page);
        setPaginationKey((prev) => prev + 1);
    };

    if (isSubscriptionLoading) {
        return (
            <div className="wpuf-flex wpuf-h-svh wpuf-items-center wpuf-justify-center">
                <Spinner />
            </div>
        );
    }

    if (!count) {
        return (
            <div className="wpuf-pl-[48px]">
                <ListHeader message={headerMessage[currentSubscriptionStatus] || headerMessage.all} />
                <Empty message={emptyMessages[currentSubscriptionStatus] || emptyMessages.all} />
            </div>
        );
    }

    return (
        <div className="wpuf-pl-[48px]">
            <ListHeader message={headerMessage[currentSubscriptionStatus] || headerMessage.all} />
            <div className="wpuf-grid wpuf-grid-cols-3 wpuf-gap-4 wpuf-mt-[40px]">
                {subscriptionList.map((subscription) => (
                    <SubscriptionBox key={subscription.ID} subscription={subscription} />
                ))}
            </div>
            {count > perPage && (
                <Pagination
                    key={paginationKey}
                    currentPage={currentPage}
                    count={count}
                    maxVisibleButtons={maxVisibleButtons}
                    totalPages={totalPages}
                    perPage={perPage}
                    onChangePageTo={changePageTo}
                />
            )}
        </div>
    );
}

// assets/js/components/subscriptions/List.vue
<script setup>
import SubscriptionBox from './SubscriptionBox.vue';
import Empty from './Empty.vue';
import {useSubscriptionStore} from '../../stores/subscription';
import {storeToRefs} from 'pinia';
import Pagination from './Pagination.vue';
import {onBeforeMount, ref, watch} from 'vue';
import ListHeader from './ListHeader.vue';
import {HollowDotsSpinner} from 'epic-spinners';
import {__} from '@wordpress/i18n';

const subscriptionStore = useSubscriptionStore();
const subscriptions = storeToRefs( subscriptionStore ).subscriptionList;
const count = ref( subscriptionStore.allCount.all );
const currentPage = ref( 1 );
const perPage = parseInt( wpufSubscriptions.perPage );
const totalPages = ref( Math.ceil( count.value / wpufSubscriptions.perPage ) );
const changePageTo = ( page ) => {
    const offset = ( page - 1 ) * parseInt( wpufSubscriptions.perPage );
    currentPage.value = page;

    subscriptionStore.setSubscriptionsByStatus( subscriptionStore.currentSubscriptionStatus, offset );
};
const maxVisibleButtons = ref( 3 );
const paginationKey = ref( 0 );

const emptyMessages = {
    all: __( 'Powerful Subscription Features for Monetizing Your Content. Unlock a World of Possibilities with WPUF\'s Subscription Features – From Charging Users for Posting to Exclusive Content Access.',
        'wp-user-frontend' ),
    publish: __( 'Ops! It looks like you haven\'t published any subscriptions yet. To create a new subscription and start monetizing your content, click the \'Add Subscription\' button above.', 'wp-user-frontend' ),
    draft: __( 'Ops! It looks like you haven\'t saved any subscriptions as drafts yet.', 'wp-user-frontend' ),
    trash: __( 'Your trash is empty! If you delete a subscription, it will be moved here.', 'wp-user-frontend' ),
};

const headerMessage = {
    all: __( 'Manage and monitor all your subscriptions. Edit details or create new ones as needed.', 'wp-user-frontend' ),
    publish: __( 'Oversee all active subscriptions currently available for users.', 'wp-user-frontend' ),
    draft: __( 'Handle subscriptions that are saved as drafts but not yet published.', 'wp-user-frontend' ),
    trash: __( 'Review deleted subscriptions. Restore or permanently delete them as required.', 'wp-user-frontend' ),
};

onBeforeMount(
    () => {
        count.value = subscriptionStore.allCount[subscriptionStore.currentSubscriptionStatus];
        totalPages.value = Math.ceil( count.value / wpufSubscriptions.perPage );
    }
);

watch(
    () => subscriptionStore.currentSubscriptionStatus,
    ( newValue ) => {
        count.value = subscriptionStore.allCount[newValue];
        totalPages.value = Math.ceil( count.value / wpufSubscriptions.perPage );
        currentPage.value = 1;
    }
);

watch(
    () => subscriptionStore.allCount,
    ( newValue ) => {
        count.value = subscriptionStore.allCount[subscriptionStore.currentSubscriptionStatus];
        totalPages.value = Math.ceil( count.value / wpufSubscriptions.perPage );

        // refresh the pagination component
        paginationKey.value += 1;
    }
);

</script>

<template>
    <div v-if="subscriptionStore.isSubscriptionLoading"
         class="wpuf-flex wpuf-h-svh wpuf-items-center wpuf-justify-center">
        <hollow-dots-spinner
            :animation-duration="1000"
            :dot-size="20"
            :dots-num="3"
            :color="'#7DC442'"
        />
    </div>
    <div v-if="!subscriptionStore.isSubscriptionLoading">
        <div v-if="!count" class="wpuf-px-8 wpuf-pb-8">
            <ListHeader :message="headerMessage[subscriptionStore.currentSubscriptionStatus]" />
            <Empty :message="emptyMessages[subscriptionStore.currentSubscriptionStatus]"/>
        </div>
        <div v-else class="wpuf-px-8 wpuf-pb-8">
            <ListHeader :message="headerMessage[subscriptionStore.currentSubscriptionStatus]" />
            <div class="wpuf-grid wpuf-grid-cols-3 wpuf-gap-4 wpuf-mt-4">
                <SubscriptionBox
                    v-for="subscription in subscriptions"
                    :subscription=subscription
                    :key="subscription.ID"/>
            </div>
        </div>
        <Pagination
            v-if="count > perPage"
            :key="paginationKey"
            :currentPage="currentPage"
            :count="count"
            :maxVisibleButtons="maxVisibleButtons"
            :totalPages="totalPages"
            :perPage="perPage"
            @changePageTo="changePageTo"/>
    </div>
</template>
