// admin/forms-list/src/components/Pagination.jsx
/**
 * Pagination component — previous/next buttons and page number range.
 *
 * @since WPUF_SINCE
 */
import { useMemo } from '@wordpress/element';
import { __ } from '@wordpress/i18n';

const Pagination = ( { currentPage, totalPages, onPageChange } ) => {
    const paginationRange = useMemo( () => {
        if ( totalPages <= 1 ) {
            return [];
        }

        const delta = 2;
        const start = Math.max( 1, currentPage - delta );
        const end = Math.min( totalPages, currentPage + delta );
        const range = [];

        for ( let i = start; i <= end; i++ ) {
            range.push( i );
        }

        return range;
    }, [ currentPage, totalPages ] );

    if ( totalPages <= 1 ) {
        return null;
    }

    const changePage = ( page ) => {
        if ( page < 1 || page > totalPages || page === currentPage ) {
            return;
        }
        onPageChange( page );
    };

    return (
        <div className="wpuf-flex wpuf-items-center wpuf-justify-center wpuf-mt-20">
            <nav className="wpuf-flex wpuf-items-center wpuf-w-full">
                <div>
                    <button
                        onClick={ () => changePage( currentPage - 1 ) }
                        disabled={ currentPage === 1 }
                        className={
                            'wpuf-mr-3 wpuf-rounded-md wpuf-relative wpuf-inline-flex wpuf-items-center wpuf-text-sm wpuf-font-medium wpuf-text-gray-700 hover:wpuf-text-primary' +
                            ( currentPage === 1 ? ' wpuf-cursor-not-allowed wpuf-opacity-50' : '' )
                        }
                    >
                        <svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path fillRule="evenodd" clipRule="evenodd" d="M7.70711 14.7071C7.31658 15.0976 6.68342 15.0976 6.2929 14.7071L2.29289 10.7071C1.90237 10.3166 1.90237 9.68342 2.29289 9.29289L6.29289 5.29289C6.68342 4.90237 7.31658 4.90237 7.70711 5.29289C8.09763 5.68342 8.09763 6.31658 7.70711 6.70711L5.41421 9L17 9C17.5523 9 18 9.44771 18 10C18 10.5523 17.5523 11 17 11L5.41421 11L7.70711 13.2929C8.09763 13.6834 8.09763 14.3166 7.70711 14.7071Z" fill="#94A3B8" />
                        </svg>
                        &nbsp;
                        { __( 'Previous', 'wp-user-frontend' ) }
                    </button>
                </div>

                <div className="wpuf-flex wpuf-items-center">
                    { paginationRange.map( ( page ) => (
                        <span
                            key={ page }
                            onClick={ () => changePage( page ) }
                            className={
                                'wpuf-relative wpuf-inline-flex wpuf-items-center wpuf-px-4 wpuf-py-2 wpuf-text-sm wpuf-font-medium wpuf-cursor-pointer wpuf-mx-1 wpuf-border-t-2 hover:wpuf-border-primary wpuf-transition-all ' +
                                ( page === currentPage
                                    ? 'wpuf-text-primary wpuf-border-primary'
                                    : 'wpuf-text-gray-500 wpuf-border-transparent' )
                            }
                        >
                            { page }
                        </span>
                    ) ) }
                </div>

                <div>
                    <button
                        onClick={ () => changePage( currentPage + 1 ) }
                        disabled={ currentPage === totalPages }
                        className={
                            'wpuf-ml-3 wpuf-rounded-md wpuf-relative wpuf-inline-flex wpuf-items-center wpuf-text-sm wpuf-font-medium wpuf-text-gray-700 hover:wpuf-text-primary' +
                            ( currentPage === totalPages ? ' wpuf-cursor-not-allowed wpuf-opacity-50' : '' )
                        }
                    >
                        { __( 'Next', 'wp-user-frontend' ) }
                        &nbsp;
                        <svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path fillRule="evenodd" clipRule="evenodd" d="M12.2929 5.29289C12.6834 4.90237 13.3166 4.90237 13.7071 5.29289L17.7071 9.29289C18.0976 9.68342 18.0976 10.3166 17.7071 10.7071L13.7071 14.7071C13.3166 15.0976 12.6834 15.0976 12.2929 14.7071C11.9024 14.3166 11.9024 13.6834 12.2929 13.2929L14.5858 11H3C2.44772 11 2 10.5523 2 10C2 9.44772 2.44772 9 3 9H14.5858L12.2929 6.70711C11.9024 6.31658 11.9024 5.68342 12.2929 5.29289Z" fill="#94A3B8" />
                        </svg>
                    </button>
                </div>
            </nav>
        </div>
    );
};

export default Pagination;

// assets/js/components/subscriptions/Pagination.vue
<script setup>
import {computed, ref, toRef} from 'vue';

const props = defineProps({
    count: {
        type: Number,
        required: true
    },
    maxVisibleButtons: {
        type: Number,
        required: false,
        default: 3
    },
    totalPages: {
        type: Number,
        required: true
    }
});

const count = ref(props.count);
const maxVisibleButtons = ref(props.maxVisibleButtons);
const totalPages = ref(props.totalPages);
const emit = defineEmits( ['changePageTo'] );

const perPage = wpufSubscriptions.perPage;
const startPage = computed(() => {
    // When on the first page, or when the total pages are less than the max visible buttons
    if (currentPage.value === 1 || totalPages.value <= maxVisibleButtons.value) {
        return 1;
    }

    // When on the last page
    if (currentPage.value === totalPages.value) {
        return totalPages.value - maxVisibleButtons.value;
    }

    // When in-between
    return currentPage.value - 1;
});
const pages = computed(() => {
    const range = [];
    for (
        let i = startPage.value;
        i <= Math.min(startPage.value + maxVisibleButtons.value - 1, totalPages.value);
        i++
    ) {
        range.push({
            name: i,
            isDisabled: i === currentPage
        });
    }

    return range;
});
const isInFirstPage = computed(() => currentPage.value === 1);
const isInLastPage = computed(() => currentPage.value === totalPages.value);
const currentPage = ref( 1 );
const startNumber = computed(() => {
    return (currentPage.value - 1) * perPage + 1;
});
const endNumber = computed(() => {
    return Math.min(currentPage.value * perPage, count.value);
});

const goToFirstPage = () => {
    currentPage.value = 1;

    emit('changePageTo', 1);
};
const goToLastPage = () => {
    currentPage.value = totalPages.value;

    emit('changePageTo', totalPages.value);
};

</script>
<template>
    <div class="wpuf-flex wpuf-items-center wpuf-justify-between wpuf-border-t wpuf-border-gray-200 wpuf-bg-white wpuf-px-4 wpuf-py-3 wpuf-px-6">
        <div class="wpuf-flex wpuf-flex-1 wpuf-justify-between wpuf-hidden">
            <a href="#" class="wpuf-relative wpuf-inline-flex wpuf-items-center wpuf-rounded-md wpuf-border wpuf-border-gray-300 wpuf-bg-white wpuf-px-4 wpuf-py-2 wpuf-text-sm wpuf-font-medium wpuf-text-gray-700 hover:wpuf-bg-gray-50">Previous</a>
            <a href="#" class="wpuf-relative wpuf-ml-3 wpuf-inline-flex wpuf-items-center wpuf-rounded-md wpuf-border wpuf-border-gray-300 wpuf-bg-white wpuf-px-4 wpuf-py-2 wpuf-text-sm wpuf-font-medium wpuf-text-gray-700 hover:wpuf-bg-gray-50">Next</a>
        </div>
        <div class="wpuf-hidden wpuf-flex wpuf-flex-1 wpuf-items-center wpuf-justify-between">
            <div>
                <p class="wpuf-text-sm wpuf-text-gray-700">
                    Showing
                    <span class="wpuf-font-medium">{{ startNumber }}</span>
                    to
                    <span class="wpuf-font-medium">{{ endNumber }}</span>
                    of
                    <span class="wpuf-font-medium">{{ count }}</span>
                    results
                </p>
            </div>
            <div>
                <nav class="isolate wpuf-inline-flex wpuf--space-x-px wpuf-rounded-md wpuf-shadow-sm" aria-label="Pagination">
                    <button
                        @click="goToFirstPage"
                        :disabled="isInFirstPage"
                        href="#"
                        :class="isInFirstPage ? 'wpuf-bg-gray-50 wpuf-cursor-not-allowed' : ''"
                        class="wpuf-relative wpuf-inline-flex wpuf-items-center wpuf-rounded-l-md wpuf-px-2 wpuf-py-2 wpuf-text-gray-400 wpuf-ring-1 wpuf-ring-inset wpuf-ring-gray-300 hover:wpuf-bg-gray-50 focus:wpuf-z-20 focus:outline-offset-0">
                        <span class="wpuf-sr-only">Previous</span>
                        <svg class="wpuf-h-5 wpuf-w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                            <path fill-rule="evenodd" d="M12.79 5.23a.75.75 0 01-.02 1.06L8.832 10l3.938 3.71a.75.75 0 11-1.04 1.08l-4.5-4.25a.75.75 0 010-1.08l4.5-4.25a.75.75 0 011.06.02z" clip-rule="evenodd" />
                        </svg>
                    </button>
                    <button
                        v-for="page in pages"
                        @click="[emit('changePageTo', page.name), currentPage = page.name]"
                        :key="page.name"
                        :class="currentPage === page.name ? 'wpuf-bg-indigo-600 wpuf-text-white hover:wpuf-bg-indigo-700' : ''"
                        class="wpuf-relative wpuf-items-center wpuf-px-4 wpuf-py-2 wpuf-text-sm wpuf-font-semibold wpuf-text-gray-900 wpuf-ring-1 wpuf-ring-inset wpuf-ring-gray-300 hover:wpuf-bg-gray-50 focus:wpuf-z-20 focus:outline-offset-0 wpuf-inline-flex">
                        {{ page.name }}
                    </button>
                    <button
                        @click="goToLastPage"
                        :class="isInLastPage ? 'wpuf-bg-gray-50 wpuf-cursor-not-allowed' : ''"
                        class="wpuf-relative wpuf-inline-flex wpuf-items-center wpuf-rounded-r-md wpuf-px-2 wpuf-py-2 wpuf-text-gray-400 wpuf-ring-1 wpuf-ring-inset wpuf-ring-gray-300 hover:wpuf-bg-gray-50 focus:wpuf-z-20 focus:outline-offset-0">
                        <span class="wpuf-sr-only">Next</span>
                        <svg class="wpuf-h-5 wpuf-w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                            <path fill-rule="evenodd" d="M7.21 14.77a.75.75 0 01.02-1.06L11.168 10 7.23 6.29a.75.75 0 111.04-1.08l4.5 4.25a.75.75 0 010 1.08l-4.5 4.25a.75.75 0 01-1.06-.02z" clip-rule="evenodd" />
                        </svg>
                    </button>
                </nav>
            </div>
        </div>
    </div>
</template>
