// src/js/components/subscriptions/SidebarMenu.jsx
/**
 * DESCRIPTION: SidebarMenu component for Subscriptions page
 * DESCRIPTION: Displays navigation menu with status filters and counts
 */
import { __ } from '@wordpress/i18n';

const SidebarMenu = ( {
	currentSubscriptionStatus = 'all',
	allCount = {},
	onCheckIsDirty,
	isUnsavedPopupOpen = false,
} ) => {
	const statusItems = [
		{ key: 'all', label: __( 'All Subscriptions', 'wp-user-frontend' ) },
		{ key: 'publish', label: __( 'Published', 'wp-user-frontend' ) },
		{ key: 'draft', label: __( 'Drafts', 'wp-user-frontend' ) },
		{ key: 'trash', label: __( 'Trash', 'wp-user-frontend' ) },
		{ key: 'preferences', label: __( 'Preferences', 'wp-user-frontend' ) },
	];

	return (
		<div className={ isUnsavedPopupOpen ? 'wpuf-blur' : '' }>
			<div className="wpuf-flex wpuf-flex-col">
				<ul className="wpuf-space-y-2 wpuf-text-lg">
					{ statusItems.map( ( item ) => {
						const count = allCount[ item.key ] || 0;
						const isActive = currentSubscriptionStatus === item.key;

						return (
							<li
								key={ item.key }
								onClick={ () => onCheckIsDirty && onCheckIsDirty( item.key ) }
								className={
									'wpuf-justify-between wpuf-text-gray-700 hover:wpuf-text-primary hover:wpuf-bg-gray-50 group wpuf-flex wpuf-gap-x-3 wpuf-rounded-md wpuf-py-2 wpuf-px-[20px] wpuf-text-sm wpuf-leading-6 hover:wpuf-cursor-pointer' +
									( isActive ? ' wpuf-bg-gray-50 wpuf-text-primary' : '' )
								}
							>
								{ item.label }
								{ count > 0 && (
									<span
										className={
											'wpuf-text-sm wpuf-w-fit wpuf-px-2.5 wpuf-py-1 wpuf-rounded-full wpuf-w-max wpuf-h-max wpuf-border' +
											( isActive ? ' wpuf-border-primary' : '' )
										}
									>
										{ count }
									</span>
								) }
							</li>
						);
					} ) }
				</ul>
			</div>
		</div>
	);
};

export default SidebarMenu;

// assets/js/components/subscriptions/SidebarMenu.vue
<script setup>
import { __ } from '@wordpress/i18n';
import {useSubscriptionStore} from '../../stores/subscription';

const subscriptionStore = useSubscriptionStore();

</script>
<template>
    <div
    :class="subscriptionStore.isUnsavedPopupOpen ? 'wpuf-blur' : ''">
        <div class="wpuf-flex wpuf-flex-col wpuf-min-h-screen wpuf-pr-[48px]">
            <div class="wpuf-flex wpuf-items-center wpuf-justify-between wpuf-mb-[40px] wpuf-leading-none">
                <h3 class="wpuf-text-[24px] wpuf-font-semibold wpuf-my-0">{{ __('Subscriptions', 'wp-user-frontend') }}</h3>
            </div>
            <ul class="wpuf-space-y-2 wpuf-text-lg">
                <li
                    @click="$emit('checkIsDirty', 'all')"
                    :class="subscriptionStore.currentSubscriptionStatus === 'all' ? 'wpuf-bg-gray-50 wpuf-text-indigo-600' : ''"
                    class="wpuf-justify-between wpuf-text-gray-700 hover:wpuf-text-indigo-600 hover:wpuf-bg-gray-50 group wpuf-flex wpuf-gap-x-3 wpuf-rounded-md wpuf-py-2 wpuf-px-[20px] wpuf-text-sm wpuf-leading-6 hover:wpuf-cursor-pointer">
                    {{ __('All Subscriptions', 'wp-user-frontend') }}
                    <span
                        v-if="subscriptionStore.allCount.all > 0"
                        class="wpuf-text-sm wpuf-w-fit wpuf-px-2.5 wpuf-py-1 wpuf-shadow-sm wpuf-rounded-full wpuf-ring-1 wpuf-w-max wpuf-h-max">
                        {{ subscriptionStore.allCount.all }}
                    </span>
                </li>
                <li
                    @click="$emit('checkIsDirty', 'publish')"
                    :class="subscriptionStore.currentSubscriptionStatus === 'publish' ? 'wpuf-bg-gray-50' : ''"
                    class="wpuf-justify-between wpuf-text-gray-700 hover:wpuf-text-indigo-600 hover:wpuf-bg-gray-50 group wpuf-flex wpuf-gap-x-3 wpuf-rounded-md wpuf-py-2 wpuf-px-[20px] wpuf-text-sm wpuf-leading-6 hover:wpuf-cursor-pointer">
                    {{ __('Published', 'wp-user-frontend') }}
                    <span
                        v-if="subscriptionStore.allCount.publish > 0"
                        class="wpuf-text-sm wpuf-w-fit wpuf-px-2.5 wpuf-py-1 wpuf-shadow-sm wpuf-rounded-full wpuf-ring-1 wpuf-w-max wpuf-h-max">
                        {{ subscriptionStore.allCount.publish }}
                    </span>
                </li>
                <li
                    @click="$emit('checkIsDirty', 'draft')"
                    :class="subscriptionStore.currentSubscriptionStatus === 'draft' ? 'wpuf-bg-gray-50 wpuf-text-indigo-600' : ''"
                    class="wpuf-justify-between wpuf-text-gray-700 hover:wpuf-text-indigo-600 hover:wpuf-bg-gray-50 group wpuf-flex wpuf-gap-x-3 wpuf-rounded-md wpuf-py-2 wpuf-px-[20px] wpuf-text-sm wpuf-leading-6 hover:wpuf-cursor-pointer">
                    {{ __('Drafts', 'wp-user-frontend') }}
                    <span
                        v-if="subscriptionStore.allCount.draft > 0"
                        class="wpuf-text-sm wpuf-w-fit wpuf-px-2.5 wpuf-py-1 wpuf-shadow-sm wpuf-rounded-full wpuf-ring-1 wpuf-w-max wpuf-h-max">
                        {{ subscriptionStore.allCount.draft }}
                    </span>
                </li>
                <li
                    @click="$emit('checkIsDirty', 'trash')"
                    :class="subscriptionStore.currentSubscriptionStatus === 'trash' ? 'wpuf-bg-gray-50 wpuf-text-indigo-600' : ''"
                    class="wpuf-justify-between wpuf-text-gray-700 hover:wpuf-text-indigo-600 hover:wpuf-bg-gray-50 group wpuf-flex wpuf-gap-x-3 wpuf-rounded-md wpuf-py-2 wpuf-px-[20px] wpuf-text-sm wpuf-leading-6 hover:wpuf-cursor-pointer">
                    {{ __('Trash', 'wp-user-frontend') }}
                    <span
                        v-if="subscriptionStore.allCount.trash > 0"
                        class="wpuf-text-sm wpuf-w-fit wpuf-px-2.5 wpuf-py-1 wpuf-shadow-sm wpuf-rounded-full wpuf-ring-1 wpuf-w-max wpuf-h-max">
                        {{ subscriptionStore.allCount.trash }}
                    </span>
                </li>
            </ul>
        </div>
    </div>
</template>
