// assets/js/components/subscriptions/Edit.vue
<script setup>
import {__} from '@wordpress/i18n';
import InfoCard from './InfoCard.vue';
import SubscriptionsDetails from './SubscriptionsDetails.vue';
import {useComponentStore} from '../../stores/component';
import {useSubscriptionStore} from '../../stores/subscription';
import {ref} from 'vue';
import UpdateButton from './UpdateButton.vue';
import {useNoticeStore} from '../../stores/notice';
import Unsaved from './Unsaved.vue';

const componentStore = useComponentStore();
const subscriptionStore = useSubscriptionStore();
const noticeStore = useNoticeStore();

const updateSubscription = () => {
    subscriptionStore.resetErrors();

    if(!subscriptionStore.validateFields()) {
        subscriptionStore.isUpdating = false;

        return;
    }

    const promiseResult = subscriptionStore.updateSubscription();

    promiseResult.then((result) => {
        if (result.success) {
            noticeStore.display = true;
            noticeStore.type = 'success';
            noticeStore.message = result.message;
        } else {
            noticeStore.display = true;
            noticeStore.type = 'danger';
            noticeStore.message = result.message;
        }

        subscriptionStore.isUpdating = false;

        setTimeout(() => {
            noticeStore.display = false;
            noticeStore.type = '';
            noticeStore.message = '';
        }, 3000);

        componentStore.setCurrentComponent( 'List' );
    });
};

const goToList = () => {
    subscriptionStore.isDirty = false;
    subscriptionStore.isUnsavedPopupOpen = false;

    componentStore.setCurrentComponent('List');
    subscriptionStore.setCurrentSubscription(null);
};

</script>
<template>
    <div
        :class="subscriptionStore.isUnsavedPopupOpen ? 'wpuf-blur' : ''"
        class="wpuf-px-12">
        <div class="wpuf-flex wpuf-justify-between">
            <button
                type="button"
                @click="subscriptionStore.isDirty ? subscriptionStore.isUnsavedPopupOpen = subscriptionStore.isDirty : goToList()"
                class="wpuf-rounded-md wpuf-bg-indigo-600 wpuf-px-3 wpuf-py-2 wpuf-text-sm wpuf-font-semibold wpuf-text-white wpuf-shadow-sm hover:wpuf-bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">
                <span class="dashicons dashicons-arrow-left-alt"></span>&nbsp;{{ __( 'Back', 'wp-user-frontend' ) }}</button>
        </div>
        <h3 class="wpuf-text-lg wpuf-font-bold wpuf-mb-0">{{ __( 'Edit', 'wp-user-frontend' ) }}</h3>
        <InfoCard />
        <SubscriptionsDetails />
        <div class="wpuf-mt-8 wpuf-text-end">
            <UpdateButton
                @update-subscription="updateSubscription"
                :is-updating="isUpdating" />
        </div>
    </div>
    <Unsaved v-if="subscriptionStore.isUnsavedPopupOpen" @close-popup="subscriptionStore.isUnsavedPopupOpen = false" @go-to-list="goToList" />
</template>

// src/js/components-react/subscriptions/Edit.jsx
import { __ } from '@wordpress/i18n';
import { useSelect, useDispatch } from '@wordpress/data';
import { useCallback } from '@wordpress/element';
import InfoCard from './InfoCard';
import SubscriptionsDetails from './SubscriptionsDetails';
import UpdateButton from './UpdateButton';

export default function Edit({ onGoToList, onCheckIsDirty }) {
    const { isUnsavedPopupOpen, currentSubscriptionStatus } = useSelect((select) => {
        const store = select('wpuf/subscriptions');
        return {
            isUnsavedPopupOpen: store.isUnsavedPopupOpen(),
            currentSubscriptionStatus: store.getCurrentStatus(),
        };
    }, []);

    const {
        resetErrors,
        validateFields,
        updateItem,
        setIsDirty,
        setIsUnsavedPopupOpen,
        setSubscriptionsByStatus,
        getSubscriptionCount,
        setItem,
    } = useDispatch('wpuf/subscriptions');

    const { setCurrentComponent } = useDispatch('wpuf/subscriptions-component');
    const { addNotice } = useDispatch('wpuf/subscriptions-notice');

    const updateSubscription = useCallback(async () => {
        resetErrors();

        const isValid = validateFields();
        if (!isValid) {
            return;
        }

        try {
            const result = await updateItem();
            if (result && result.success) {
                addNotice({
                    type: 'success',
                    message: result.message,
                });

                await setSubscriptionsByStatus(currentSubscriptionStatus);
                getSubscriptionCount();

                if (onGoToList) {
                    onGoToList();
                }
            } else if (result && !result.success) {
                addNotice({
                    type: 'danger',
                    message: result.message,
                });
            }
        } catch (error) {
            console.error('Update error:', error);
            addNotice({
                type: 'danger',
                message: __('An error occurred while updating the subscription.', 'wp-user-frontend'),
            });
        }
    }, [resetErrors, validateFields, updateItem, currentSubscriptionStatus, setSubscriptionsByStatus, getSubscriptionCount, addNotice, onGoToList]);

    return (
        <div className={`wpuf-px-12 ${isUnsavedPopupOpen ? 'wpuf-blur' : ''}`}>
            <h3 className="wpuf-text-lg wpuf-font-bold wpuf-mb-0">{__('Edit Subscription', 'wp-user-frontend')}</h3>
            <InfoCard />
            <SubscriptionsDetails />
            <div className="wpuf-flex wpuf-flex-row-reverse wpuf-mt-8 wpuf-text-end">
                <UpdateButton onUpdateSubscription={updateSubscription} />
                <button
                    onClick={() => onCheckIsDirty && onCheckIsDirty(currentSubscriptionStatus)}
                    type="button"
                    className="wpuf-mr-[10px] wpuf-rounded-md wpuf-bg-white wpuf-px-3 wpuf-py-2 wpuf-text-sm wpuf-font-semibold wpuf-text-gray-900 wpuf-shadow-sm wpuf-ring-1 wpuf-ring-inset wpuf-ring-gray-300 hover:wpuf-bg-gray-50"
                >
                    {__('Cancel', 'wp-user-frontend')}
                </button>
            </div>
        </div>
    );
}
