// assets/js/components/subscriptions/New.vue
<script setup>
import {__} from '@wordpress/i18n';
import SubscriptionsDetails from './SubscriptionsDetails.vue';
import {useComponentStore} from '../../stores/component';
import {useSubscriptionStore} from '../../stores/subscription';
import {onBeforeMount, ref} from 'vue';
import UpdateButton from './UpdateButton.vue';
import {useNoticeStore} from '../../stores/notice';

const componentStore = useComponentStore();
const subscriptionStore = useSubscriptionStore();
const noticeStore = useNoticeStore();

onBeforeMount(() => {
    subscriptionStore.setBlankSubscription();
});

const updateSubscription = () => {
    subscriptionStore.isUpdating = true;
    subscriptionStore.resetErrors();

    if(!subscriptionStore.validateFields()) {
        subscriptionStore.isUpdating = false;

        return;
    }

    subscriptionStore.isSubscriptionLoading = true;

    const promiseResult = subscriptionStore.updateSubscription();

    promiseResult.then((result) => {
        if (result.success) {
            noticeStore.display = true;
            noticeStore.type = 'success';
            noticeStore.message = result.message;

            subscriptionStore.setSubscriptionsByStatus( subscriptionStore.currentSubscriptionStatus );
            componentStore.setCurrentComponent( 'List' );
            subscriptionStore.getSubscriptionCount();
        } else {
            noticeStore.display = true;
            noticeStore.type = 'danger';
            noticeStore.message = result.message;
        }

        subscriptionStore.isUpdating = false;

        setTimeout(() => {
            noticeStore.display = false;
            noticeStore.type = '';
            noticeStore.message = '';
        }, 3000);

    }).finally(() => {
        subscriptionStore.isSubscriptionLoading = false;
    });
};

</script>
<template>
    <div class="wpuf-px-12">
        <h3 class="wpuf-text-lg wpuf-font-bold wpuf-mb-0">{{ __( 'New Subscription', 'wp-user-frontend' ) }}</h3>
        <SubscriptionsDetails />
        <div class="wpuf-flex wpuf-flex-row-reverse wpuf-mt-8 wpuf-text-end">
            <UpdateButton
                buttonText="Save"
                @update-subscription="updateSubscription" />
            <button
                @click="$emit('checkIsDirty', subscriptionStore.currentSubscriptionStatus)"
                type="button"
                class="wpuf-mr-[10px] wpuf-rounded-md wpuf-bg-white wpuf-px-3 wpuf-py-2 wpuf-text-sm wpuf-font-semibold wpuf-text-gray-900 wpuf-shadow-sm wpuf-ring-1 wpuf-ring-inset wpuf-ring-gray-300 hover:wpuf-bg-gray-50">
                {{ __( 'Cancel', 'wp-user-frontend' ) }}
            </button>
        </div>
    </div>
</template>

// src/js/components-react/subscriptions/New.jsx
import { __ } from '@wordpress/i18n';
import { useEffect, useCallback } from '@wordpress/element';
import { useSelect, useDispatch } from '@wordpress/data';
import SubscriptionsDetails from './SubscriptionsDetails';
import UpdateButton from './UpdateButton';

export default function New({ onGoToList, onCheckIsDirty }) {
    const { currentSubscriptionStatus } = useSelect((select) => {
        const store = select('wpuf/subscriptions');
        return {
            currentSubscriptionStatus: store.getCurrentStatus(),
        };
    }, []);

    const {
        setBlankItem,
        resetErrors,
        validateFields,
        updateItem,
        setSubscriptionsByStatus,
        getSubscriptionCount,
    } = useDispatch('wpuf/subscriptions');

    const { setCurrentComponent } = useDispatch('wpuf/subscriptions-component');
    const { addNotice } = useDispatch('wpuf/subscriptions-notice');

    useEffect(() => {
        setBlankItem();
    }, [setBlankItem]);

    const updateSubscription = useCallback(async () => {
        resetErrors();

        const isValid = validateFields();
        if (!isValid) {
            return;
        }

        try {
            const result = await updateItem();
            if (result && result.success) {
                addNotice({
                    type: 'success',
                    message: result.message,
                });

                await setSubscriptionsByStatus(currentSubscriptionStatus);
                setCurrentComponent('List');
                getSubscriptionCount();
            } else if (result && !result.success) {
                addNotice({
                    type: 'danger',
                    message: result.message,
                });
            }
        } catch (error) {
            console.error('Create error:', error);
            addNotice({
                type: 'danger',
                message: __('An error occurred while creating the subscription.', 'wp-user-frontend'),
            });
        }
    }, [resetErrors, validateFields, updateItem, currentSubscriptionStatus, setSubscriptionsByStatus, getSubscriptionCount, setCurrentComponent, addNotice]);

    return (
        <div className="wpuf-px-12">
            <h3 className="wpuf-text-lg wpuf-font-bold wpuf-mb-0">{__('New Subscription', 'wp-user-frontend')}</h3>
            <SubscriptionsDetails />
            <div className="wpuf-flex wpuf-flex-row-reverse wpuf-mt-8 wpuf-text-end">
                <UpdateButton onUpdateSubscription={updateSubscription} />
                <button
                    onClick={() => onCheckIsDirty && onCheckIsDirty(currentSubscriptionStatus)}
                    type="button"
                    className="wpuf-mr-[10px] wpuf-rounded-md wpuf-bg-white wpuf-px-3 wpuf-py-2 wpuf-text-sm wpuf-font-semibold wpuf-text-gray-900 wpuf-shadow-sm wpuf-ring-1 wpuf-ring-inset wpuf-ring-gray-300 hover:wpuf-bg-gray-50"
                >
                    {__('Cancel', 'wp-user-frontend')}
                </button>
            </div>
        </div>
    );
}
