// src/js/components-react/Subscriptions.jsx
import { useState, useEffect, useCallback, useMemo } from '@wordpress/element';
import { useSelect, useDispatch } from '@wordpress/data';
import { Spinner } from '@wordpress/components';
import { __ } from '@wordpress/i18n';

// Stores
import '../stores-react/subscription';
import '../stores-react/component';
import '../stores-react/notice';
import '../stores-react/quickEdit';

// Components
import Header from './Header';
import SidebarMenu from './subscriptions/SidebarMenu';
import List from './subscriptions/List';
import Empty from './subscriptions/Empty';
import Edit from './subscriptions/Edit';
import New from './subscriptions/New';
import Preferences from './subscriptions/Preferences';
import QuickEdit from './subscriptions/QuickEdit';
import Notice from './subscriptions/Notice';
import Unsaved from './subscriptions/Unsaved';
import ContentHeader from './subscriptions/ContentHeader';

export default function Subscriptions() {
    // Local state
    const [tempSubscriptionStatus, setTempSubscriptionStatus] = useState('all');
    const [tempNavigationTarget, setTempNavigationTarget] = useState(null);

    // Store selectors
    const {
        currentComponent,
    } = useSelect((select) => ({
        currentComponent: select('wpuf/subscriptions-component').getCurrentComponent(),
    }), []);

    const {
        isSubscriptionLoading,
        isDirty,
        isUnsavedPopupOpen,
        currentSubscriptionStatus,
        subscriptionList,
    } = useSelect((select) => {
        const store = select('wpuf/subscriptions');
        return {
            isSubscriptionLoading: store.isLoading(),
            isDirty: store.isDirty(),
            isUnsavedPopupOpen: store.isUnsavedPopupOpen(),
            currentSubscriptionStatus: store.getCurrentStatus(),
            subscriptionList: store.getItems(),
        };
    }, []);

    const {
        isQuickEdit,
    } = useSelect((select) => ({
        isQuickEdit: select('wpuf/subscriptions-quick-edit').isQuickEdit(),
    }), []);

    const {
        notices,
        isNoticeDisplaying,
    } = useSelect((select) => {
        const store = select('wpuf/subscriptions-notice');
        return {
            notices: store.getNotices(),
            isNoticeDisplaying: store.isDisplaying(),
        };
    }, []);

    // Store dispatchers
    const {
        setCurrentComponent,
    } = useDispatch('wpuf/subscriptions-component');

    const {
        setSubscriptionsByStatus,
        getSubscriptionCount,
        setIsUnsavedPopupOpen,
        setIsDirty,
        setCurrentStatus,
        setItem,
        setCurrentPage,
        resetErrors,
        setErrors,
    } = useDispatch('wpuf/subscriptions');

    const {
        setQuickEditStatus,
    } = useDispatch('wpuf/subscriptions-quick-edit');

    const {
        removeNotice,
    } = useDispatch('wpuf/subscriptions-notice');

    // Initial data fetch
    useEffect(() => {
        setSubscriptionsByStatus(currentSubscriptionStatus).then((result) => {
            if (result && result.subscriptions && result.subscriptions.length > 0) {
                setCurrentComponent('List');
            } else {
                setCurrentComponent('Empty');
            }
        });
        getSubscriptionCount();
    }, []);

    // Reset errors when component changes
    useEffect(() => {
        resetErrors();
    }, [currentComponent]);

    // Navigation logic
    const goToList = useCallback(() => {
        setIsDirty(false);
        setIsUnsavedPopupOpen(false);

        if (tempNavigationTarget === 'preferences') {
            setCurrentComponent('Preferences');
            setCurrentStatus('preferences');
            setTempNavigationTarget(null);
        } else {
            setSubscriptionsByStatus(tempSubscriptionStatus);
            setCurrentComponent('List');
            setItem(null);
            setCurrentPage(1);
        }
    }, [tempNavigationTarget, tempSubscriptionStatus]);

    const checkIsDirty = useCallback((subscriptionStatus = 'all') => {
        if (subscriptionStatus === 'preferences') {
            if (isDirty) {
                setIsUnsavedPopupOpen(true);
                setTempNavigationTarget('preferences');
                setTempSubscriptionStatus(currentSubscriptionStatus || 'all');
            } else {
                setCurrentComponent('Preferences');
                setCurrentStatus('preferences');
            }
        } else if (isDirty) {
            setIsUnsavedPopupOpen(true);
            setTempSubscriptionStatus(subscriptionStatus);
            setTempNavigationTarget(null);
        } else {
            setIsDirty(false);
            setIsUnsavedPopupOpen(false);

            setSubscriptionsByStatus(subscriptionStatus);
            setCurrentComponent('List');
            setItem(null);
            getSubscriptionCount();
            setCurrentPage(1);
        }
    }, [isDirty, currentSubscriptionStatus]);

    // Render component based on state
    const CurrentView = useMemo(() => {
        switch (currentComponent) {
            case 'List':
                return List;
            case 'Edit':
                return Edit;
            case 'New':
                return New;
            case 'Preferences':
                return Preferences;
            case 'Empty':
                return Empty;
            default:
                return null;
        }
    }, [currentComponent]);

    return (
        <div>
            <Header />

            {(isSubscriptionLoading || !CurrentView) && (
                <div className="wpuf-flex wpuf-h-svh wpuf-items-center wpuf-justify-center">
                    <Spinner />
                </div>
            )}

            {isQuickEdit && (
                <div
                    className="wpuf-absolute wpuf-w-full wpuf-h-screen wpuf-z-10 wpuf-left-[-20px]"
                    onClick={() => {
                        setQuickEditStatus(false);
                        setErrors({});
                    }}
                />
            )}

            {isQuickEdit && <QuickEdit />}

            <ContentHeader />

            {!isSubscriptionLoading && (
                <div className={`wpuf-flex wpuf-pt-[40px] wpuf-pr-[20px] wpuf-pl-[20px] ${isQuickEdit ? 'wpuf-blur' : ''}`}>
                    <div className="wpuf-basis-1/5 wpuf-border-r-2 wpuf-border-gray-200">
                        <SidebarMenu onCheckIsDirty={checkIsDirty} />
                    </div>
                    <div className="wpuf-basis-4/5">
                        {CurrentView && (
                            <CurrentView
                                onGoToList={goToList}
                                onCheckIsDirty={checkIsDirty}
                            />
                        )}
                    </div>
                    {isUnsavedPopupOpen && (
                        <Unsaved
                            onClose={() => setIsUnsavedPopupOpen(false)}
                            onGoToList={goToList}
                        />
                    )}
                </div>
            )}

            <div className="wpuf-fixed wpuf-top-20 wpuf-right-8 wpuf-z-10">
                {isNoticeDisplaying && notices.map((notice, index) => (
                    <Notice
                        key={`notice-${index}`}
                        index={index}
                        type={notice.type}
                        message={notice.message}
                        onRemove={() => removeNotice(index)}
                    />
                ))}
            </div>
        </div>
    );
}

// assets/js/components/Subscriptions.vue
<script setup>
import {provide, onBeforeMount, ref, watch} from 'vue';
import {storeToRefs} from 'pinia';
import { useComponentStore } from '../stores/component';

import {HollowDotsSpinner} from 'epic-spinners';

import Header from './Header.vue';
import SidebarMenu from './subscriptions/SidebarMenu.vue';
import List from './subscriptions/List.vue';
import Empty from './subscriptions/Empty.vue';
import Edit from './subscriptions/Edit.vue';
import New from './subscriptions/New.vue';
import QuickEdit from './subscriptions/QuickEdit.vue';
import {useQuickEditStore} from '../stores/quickEdit';
import Notice from './subscriptions/Notice.vue';
import {useSubscriptionStore} from '../stores/subscription';
import Unsaved from './subscriptions/Unsaved.vue';

const componentStore = useComponentStore();
const subscriptionStore = useSubscriptionStore();
const quickEditStore = useQuickEditStore();
const { currentComponent } = storeToRefs(componentStore);

const component = ref( Empty );
const tempSubscriptionStatus = ref( 'all' );

provide( 'wpufSubscriptions', wpufSubscriptions );

onBeforeMount( () => {
    const promiseResult = subscriptionStore.setSubscriptionsByStatus( subscriptionStore.currentSubscriptionStatus );
    promiseResult.then( ( result ) => {
        if (subscriptionStore.subscriptionList) {
            componentStore.setCurrentComponent( 'List' );
        } else {
            componentStore.setCurrentComponent( 'Empty' );
        }
    } );

    subscriptionStore.getSubscriptionCount();
} );

const checkIsDirty = ( subscriptionStatus = 'all' ) => {
    if (subscriptionStore.isDirty) {
        subscriptionStore.isUnsavedPopupOpen = true;
        tempSubscriptionStatus.value = subscriptionStatus;
    } else {
        subscriptionStore.isDirty = false;
        subscriptionStore.isUnsavedPopupOpen = false;

        subscriptionStore.setSubscriptionsByStatus( subscriptionStatus );
        componentStore.setCurrentComponent('List');
        subscriptionStore.setCurrentSubscription(null);
        subscriptionStore.getSubscriptionCount();
    }
};

const goToList = () => {
    subscriptionStore.isDirty = false;
    subscriptionStore.isUnsavedPopupOpen = false;

    subscriptionStore.setSubscriptionsByStatus( tempSubscriptionStatus.value );
    componentStore.setCurrentComponent('List');
    subscriptionStore.setCurrentSubscription(null);
};

watch(
    () => componentStore.currentComponent,
    (newComponent) => {
        switch ( newComponent ) {
            case 'List':
                component.value = List;
                break;
            case 'Edit':
                component.value = Edit;
                break;
            case 'New':
                component.value = New;
                break;
            default:
                component.value = Empty;
        }
    }
);

</script>

<template>
    <Header/>
    <div v-if="subscriptionStore.isUpdating" class="wpuf-flex wpuf-h-svh wpuf-items-center wpuf-justify-center">
        <hollow-dots-spinner
            :animation-duration="1000"
            :dot-size="20"
            :dots-num="3"
            :color="'#7DC442'"
        />
    </div>
    <div
        v-if="quickEditStore.isQuickEdit"
        @click="quickEditStore.isQuickEdit = false"
        class="wpuf-absolute wpuf-w-full wpuf-h-screen wpuf-z-10 wpuf-left-[-20px]"></div>
    <template v-if="quickEditStore.isQuickEdit">
        <QuickEdit />
    </template>
    <div
        v-if="!subscriptionStore.isUpdating"
        :class="quickEditStore.isQuickEdit ? 'wpuf-blur' : ''"
        class="wpuf-flex wpuf-flex-row wpuf-mt-12 wpuf-bg-white wpuf-py-8">
        <div class="wpuf-basis-1/5 wpuf-border-r-2 wpuf-border-gray-200 wpuf-100vh">
            <keep-alive>
                <SidebarMenu @check-is-dirty="checkIsDirty" />
            </keep-alive>
        </div>
        <div
            class="wpuf-basis-4/5">
            <component :is="component" @go-to-list="goToList" />
        </div>
        <Unsaved v-if="subscriptionStore.isUnsavedPopupOpen" @close-popup="subscriptionStore.isUnsavedPopupOpen = false" @goToList="goToList" />
    </div>
    <Notice />
</template>
