// assets/js/components/FormsList.vue
<script setup>
import Header from './Header.vue';
import {__} from '@wordpress/i18n';
import {ref, onMounted, computed, watch} from 'vue';
import _ from 'lodash';
import { Menu, MenuButton, MenuItems, MenuItem } from '@headlessui/vue';

const newFormUrl = wpuf_admin_script.admin_url + 'admin.php?page=wpuf-post-forms&action=add-new';
// store only counts without 0 values
const postCounts = wpuf_forms_list.post_counts;

const currentTab = ref('all');
const forms = ref([]);
const loading = ref(true);
const currentPage = ref(1);
const perPage = ref(10);
const totalPages = ref(0);
const searchTerm = ref('');
const selectAllChecked = ref(false);
const selectedForms = ref([]);

// Debounced search handler
const debouncedFetchForms = _.debounce((page, status, search) => {
  fetchForms(page, status, search);
}, 500);

const fetchForms = async (page = 1, status = 'all', search = '') => {
  try {
    loading.value = true;
    currentPage.value = page;
    let apiUrl = `/wp-json/wpuf/v1/wpuf_form?page=${page}&per_page=${perPage.value}&status=${status}`;
    if (search) {
      apiUrl += `&s=${search}`;
    }
    const response = await fetch(apiUrl,
     {
      headers: {
        'X-WP-Nonce': wpuf_forms_list.rest_nonce,
      },
    });
    const data = await response.json();

    if (data.success) {
      forms.value = data.result;
      if (data.pagination) {
        totalPages.value = data.pagination.total_pages;
      } else {
        totalPages.value = 0;
      }

      // Reset selection when forms data changes
      selectedForms.value = [];
      selectAllChecked.value = false;
    } else {
      forms.value = [];
      totalPages.value = 0;
      selectedForms.value = [];
      selectAllChecked.value = false;
    }
  } catch (error) {
    console.error('Error fetching forms:', error);
    forms.value = [];
    totalPages.value = 0;
    selectedForms.value = [];
    selectAllChecked.value = false;
  } finally {
    loading.value = false;
  }
};

const changePage = (page) => {
  if (page < 1 || page > totalPages.value || page === currentPage.value) {
    return;
  }
  fetchForms(page, currentTab.value, searchTerm.value);
};

// Select/Deselect All handler
const handleSelectAll = () => {
  if (selectAllChecked.value) {
    selectedForms.value = forms.value.map(form => form.ID);
  } else {
    selectedForms.value = [];
  }
};

// Update selectAllChecked based on individual selections
watch(selectedForms, (newSelection) => {
  if (forms.value.length > 0 && newSelection.length === forms.value.length) {
    selectAllChecked.value = true;
  } else {
    selectAllChecked.value = false;
  }
});

// Watch for changes in currentTab and fetch forms accordingly
watch(currentTab, (newTab) => {
  fetchForms(1, newTab, searchTerm.value);
});

// Watch for changes in searchTerm and fetch forms accordingly
watch(searchTerm, (newSearch) => {
  debouncedFetchForms(1, currentTab.value, newSearch);
});

const paginationRange = computed(() => {
  const range = [];
  const delta = 2; // Number of pages to show before and after current page

  for (
    let i = Math.max(1, currentPage.value - delta);
    i <= Math.min(totalPages.value, currentPage.value + delta);
    i++
  ) {
    range.push(i);
  }

  return range;
});

// Add computed property for menu items
const menuItems = computed(() => {
  if (currentTab.value === 'trash') {
    return [
      {
        label: __('Restore', 'wp-user-frontend'),
        action: 'restore',
        class: 'wpuf-text-gray-900',
        activeClass: 'wpuf-bg-primary wpuf-text-white'
      },
      {
        label: __('Delete Permanently', 'wp-user-frontend'),
        action: 'delete',
        class: 'wpuf-text-red-600',
        activeClass: 'wpuf-bg-red-500 wpuf-text-white'
      }
    ];
  }
  return [
    {
      label: __('Edit', 'wp-user-frontend'),
      action: 'edit',
      class: 'wpuf-text-gray-900',
      activeClass: 'wpuf-bg-primary wpuf-text-white'
    },
    {
      label: __('Duplicate', 'wp-user-frontend'),
      action: 'duplicate',
      class: 'wpuf-text-gray-900',
      activeClass: 'wpuf-bg-primary wpuf-text-white'
    },
    {
      label: __('Trash', 'wp-user-frontend'),
      action: 'trash',
      class: 'wpuf-text-red-600',
      activeClass: 'wpuf-bg-red-500 wpuf-text-white'
    }
  ];
});

// Function to copy text to clipboard
const copyToClipboard = async (formId, $event) => {
  const shortcode = `[wpuf_form id="${formId}"]`;
  try {
    await navigator.clipboard.writeText(shortcode);

    // Use currentTarget to reliably get the button element
    const eventElement = $event.target;
    const buttonElement = eventElement.closest('button');
    const codeElement = buttonElement.previousElementSibling;

    // Check if we found the code element and it is indeed a <code> tag
    if (codeElement && codeElement.tagName === 'CODE') {
      codeElement.textContent = 'Copied!';
      setTimeout(() => {
        // Restore the original shortcode text
        codeElement.textContent = shortcode;
      }, 2000);
    }
  } catch (err) {
    console.error('Failed to copy shortcode: ', err);
  }
};

const handleEdit = (formId) => {
  // Construct the edit URL
  const editUrl = `${wpuf_admin_script.admin_url}admin.php?page=wpuf-post-forms&action=edit&id=${formId}`;
  // Navigate to the edit page
  window.location.href = editUrl;
};

const handleDuplicate = (formId) => {
  // Generate WordPress nonce for security
  const wpnonce = wpuf_forms_list.bulk_nonce;
  // Construct the base admin URL with nonce
  const adminUrl = `${wpuf_admin_script.admin_url}admin.php?page=wpuf-post-forms&id=${formId}&_wpnonce=${wpnonce}`;
  // Construct the duplicate URL
  const duplicateUrl = `${adminUrl}&action=duplicate`;
  // Redirect to the duplicate URL
  window.location.href = duplicateUrl;
};

const handleTrash = (formId) => {
  // Generate WordPress nonce for security
  const wpnonce = wpuf_forms_list.bulk_nonce;
  // Construct the base admin URL with nonce
  const adminUrl = `${wpuf_admin_script.admin_url}admin.php?page=wpuf-post-forms&id=${formId}&_wpnonce=${wpnonce}`;
  // Construct the trash URL
  const trashUrl = `${adminUrl}&action=trash`;
  // Redirect to the trash URL
  window.location.href = trashUrl;
};

// Add new handler for restore action
const handleRestore = (formId) => {
  // Generate WordPress nonce for security
  const wpnonce = wpuf_forms_list.bulk_nonce;
  // Construct the base admin URL with nonce
  const adminUrl = `${wpuf_admin_script.admin_url}admin.php?page=wpuf-post-forms&id=${formId}&_wpnonce=${wpnonce}`;
  // Construct the restore URL
  const restoreUrl = `${adminUrl}&action=restore`;
  // Redirect to the restore URL
  window.location.href = restoreUrl;
};

// Add new handler for delete permanently action
const handleDelete = (formId) => {
  // Show confirmation dialog
  if (!confirm(__('Are you sure you want to delete this form permanently? This action cannot be undone.', 'wp-user-frontend'))) {
    return;
  }

  // Generate WordPress nonce for security
  const wpnonce = wpuf_forms_list.bulk_nonce;
  // Construct the base admin URL with nonce
  const adminUrl = `${wpuf_admin_script.admin_url}admin.php?page=wpuf-post-forms&id=${formId}&_wpnonce=${wpnonce}`;
  // Construct the delete URL
  const deleteUrl = `${adminUrl}&action=delete`;
  // Redirect to the delete URL
  window.location.href = deleteUrl;
};

onMounted(() => {
  fetchForms(1, currentTab.value, searchTerm.value);
});
</script>

<template>
  <Header utm="wpuf-form-builder" />
  <div class="wpuf-flex wpuf-justify-between wpuf-items-center wpuf-mb-4">
    <h3 class="wpuf-text-2xl wpuf-font-bold">{{ __( 'Post Forms', 'wp-user-frontend' ) }}</h3>
    <div>
      <a
        :href="newFormUrl"
        class="wpuf-rounded-md wpuf-text-center wpuf-bg-primary wpuf-px-3 wpuf-py-2 wpuf-text-sm wpuf-font-semibold wpuf-text-white wpuf-shadow-sm hover:wpuf-bg-primaryHover hover:wpuf-text-white focus:wpuf-bg-primaryHover focus:wpuf-text-white">
      <span class="dashicons dashicons-plus-alt2"></span>
      &nbsp;
      {{ __( 'Add New ', 'wp-user-frontend' ) }}
    </a>
    </div>
  </div>
  <div class="wpuf-flex">
    <span
        v-for="(value, key) in postCounts"
        :key="key"
        @click="currentTab = key"
        :class="{
          'wpuf-border-primary wpuf-text-primary': currentTab === key,
          'wpuf-border-transparent wpuf-text-gray-500 hover:wpuf-border-gray-300 hover:wpuf-text-gray-700': currentTab !== key
        }"
        class="wpuf-flex wpuf-whitespace-nowrap wpuf-py-4 wpuf-px-1 wpuf-border-b-2 wpuf-font-medium wpuf-text-sm wpuf-mr-8 focus:wpuf-outline-none focus:wpuf-shadow-none wpuf-transition-all hover:wpuf-cursor-pointer">
      {{ value.label }}
      <span class="wpuf-bg-gray-100 wpuf-text-gray-900 wpuf-ml-3 wpuf-rounded-full wpuf-py-0.5 wpuf-px-2.5 wpuf-text-xs wpuf-font-medium md:wpuf-inline-block">{{ value.count }}</span>
    </span>
  </div>
  <div class="wpuf-flex wpuf-justify-between wpuf-my-8">
    <div class="wpuf-flex">
      <select class="wpuf-block wpuf-w-full wpuf-min-w-full !wpuf-py-[10px] !wpuf-px-[14px] wpuf-text-gray-700 wpuf-font-normal !wpuf-leading-none !wpuf-shadow-sm wpuf-border !wpuf-border-gray-300 !wpuf-rounded-[6px] focus:!wpuf-ring-transparent focus:checked:!wpuf-ring-transparent hover:checked:!wpuf-ring-transparent hover:!wpuf-text-gray-700 !wpuf-text-base !leading-6">
        <option value="">{{ __( 'Bulk actions', 'wp-user-frontend' ) }}</option>
        <option value="trash">{{ __( 'Move to trash', 'wp-user-frontend' ) }}</option>
      </select>
      <button class="wpuf-ml-4 wpuf-inline-flex wpuf-items-center wpuf-justify-center wpuf-rounded-md wpuf-border wpuf-border-transparent wpuf-bg-primary wpuf-px-3 wpuf-py-2 wpuf-text-sm wpuf-font-semibold wpuf-text-white hover:wpuf-bg-primaryHover focus:wpuf-bg-primaryHover focus:wpuf-text-white">
        {{ __( 'Apply', 'wp-user-frontend' ) }}
      </button>
    </div>
    <div class="wpuf-form-search-box">
      <div class="wpuf-relative">
        <input
            type="text"
            v-model="searchTerm"
            placeholder="Search Forms"
            class="wpuf-block wpuf-min-w-full !wpuf-m-0 !wpuf-leading-none !wpuf-py-[10px] !wpuf-px-[14px] wpuf-text-gray-700 !wpuf-shadow-sm placeholder:wpuf-text-gray-400 wpuf-border !wpuf-border-gray-300 !wpuf-rounded-[6px] wpuf-max-w-full focus:!wpuf-ring-transparent"
        />
        <span class="wpuf-absolute wpuf-top-0 wpuf-right-0 wpuf-p-[10px]">
          <svg class="wpuf-h-5 wpuf-w-5 wpuf-text-gray-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
            <path fill-rule="evenodd" d="M9 3.5a5.5 5.5 0 100 11 5.5 5.5 0 000-11zM2 9a7 7 0 1112.452 4.391l3.328 3.329a.75.75 0 11-1.06 1.06l-3.329-3.328A7 7 0 012 9z" clip-rule="evenodd" />
          </svg>
        </span>
      </div>
    </div>
  </div>
  <div class="wpuf-flow-root">
    <div class="wpuf--mx-4 wpuf--my-2 wpuf-overflow-x-auto sm:wpuf--mx-6 lg:wpuf--mx-8">
      <div class="wpuf-inline-block wpuf-min-w-full wpuf-py-2 wpuf-align-middle sm:wpuf-px-6 lg:wpuf-px-8">
        <div class="wpuf-shadow wpuf-border wpuf-border-gray-200 sm:wpuf-rounded-lg">
          <table class="wpuf-min-w-full wpuf-divide-y wpuf-divide-gray-200">
            <thead>
            <tr>
              <th scope="col" class="wpuf-py-3.5 wpuf-pl-4 wpuf-pr-3 wpuf-text-left wpuf-text-sm wpuf-font-semibold wpuf-text-gray-900 sm:wpuf-pl-6">
                <input
                    type="checkbox"
                    v-model="selectAllChecked"
                    @change="handleSelectAll"
                    :indeterminate="selectedForms.length > 0 && selectedForms.length < forms.length"
                    class="!wpuf-mt-0 !wpuf-mr-2 wpuf-h-4 wpuf-w-4 !wpuf-shadow-none checked:!wpuf-shadow-none focus:checked:!wpuf-shadow-primary focus:checked:!wpuf-shadow-none !wpuf-border-gray-300 checked:!wpuf-border-primary before:checked:!wpuf-bg-white hover:checked:!wpuf-bg-primary focus:!wpuf-ring-transparent focus:checked:!wpuf-ring-transparent hover:checked:!wpuf-ring-transparent focus:checked:!wpuf-bg-primary focus:wpuf-shadow-primary checked:focus:!wpuf-bg-primary checked:hover:wpuf-bg-primary checked:!wpuf-bg-primary before:!wpuf-content-none wpuf-rounded" />
                {{ __( 'Form Name', 'wp-user-frontend' ) }}
              </th>
              <th scope="col" class="wpuf-px-3 wpuf-py-3.5 wpuf-text-left wpuf-text-sm wpuf-font-semibold wpuf-text-gray-900">{{ __( 'Post Type', 'wp-user-frontend' ) }}</th>
              <th scope="col" class="wpuf-px-3 wpuf-py-3.5 wpuf-text-left wpuf-text-sm wpuf-font-semibold wpuf-text-gray-900">{{ __( 'Post Status', 'wp-user-frontend' ) }}</th>
              <th scope="col" class="wpuf-px-3 wpuf-py-3.5 wpuf-text-left wpuf-text-sm wpuf-font-semibold wpuf-text-gray-900">{{ __( 'Shortcode', 'wp-user-frontend' ) }}</th>
              <th scope="col" class="wpuf-px-3 wpuf-py-3.5 wpuf-text-left wpuf-text-sm wpuf-font-semibold wpuf-text-gray-900">{{ __( 'Guest Post', 'wp-user-frontend' ) }}</th>
              <th scope="col" class="wpuf-px-3 wpuf-py-3.5 wpuf-text-left wpuf-text-sm wpuf-font-semibold wpuf-text-gray-900">
                <span class="wpuf-sr-only">Menu</span>
              </th>
            </tr>
            </thead>
            <tbody class="wpuf-divide-y wpuf-divide-gray-200 wpuf-bg-white">
              <tr v-if="loading">
                <td colspan="6" class="wpuf-py-4 wpuf-text-center">
                  {{ __( 'Loading...', 'wp-user-frontend' ) }}
                </td>
              </tr>
              <tr v-else-if="forms.length === 0">
                <td colspan="6" class="wpuf-py-4 wpuf-text-center">
                  {{ __( 'No forms found', 'wp-user-frontend' ) }}
                </td>
              </tr>
              <tr v-for="form in forms" :key="form.ID" class="wpuf-relative wpuf-group">
                <td class="wpuf-whitespace-nowrap wpuf-py-4 wpuf-pl-4 wpuf-pr-3 wpuf-text-sm wpuf-font-medium wpuf-text-gray-900 sm:wpuf-pl-6">
                  <input
                    type="checkbox"
                    :value="form.ID"
                    v-model="selectedForms"
                    class="!wpuf-mt-0 !wpuf-mr-2 wpuf-h-4 wpuf-w-4 !wpuf-shadow-none checked:!wpuf-shadow-none focus:checked:!wpuf-shadow-primary focus:checked:!wpuf-shadow-none !wpuf-border-gray-300 checked:!wpuf-border-primary before:checked:!wpuf-bg-white hover:checked:!wpuf-bg-primary focus:!wpuf-ring-transparent focus:checked:!wpuf-ring-transparent hover:checked:!wpuf-ring-transparent focus:checked:!wpuf-bg-primary focus:wpuf-shadow-primary checked:focus:!wpuf-bg-primary checked:hover:wpuf-bg-primary checked:!wpuf-bg-primary before:!wpuf-content-none wpuf-rounded" />
                  {{ form.post_title }}
                  <span v-if="form.post_status === 'draft'">
                    - {{ __( 'Draft', 'wp-user-frontend' ) }}
                  </span>
                </td>
                <td class="wpuf-whitespace-nowrap wpuf-px-3 wpuf-py-4 wpuf-text-sm wpuf-text-gray-500">
                  {{ form.settings_post_type }}
                </td>
                <td class="wpuf-whitespace-nowrap wpuf-px-3 wpuf-py-4 wpuf-text-sm">
                  <span
                    :class="{
                      'wpuf-bg-green-100 wpuf-text-green-800': form.post_status === 'publish',
                      'wpuf-bg-yellow-100 wpuf-text-yellow-800': form.post_status === 'pending',
                      'wpuf-bg-purple-100 wpuf-text-purple-800': form.post_status === 'private',
                      'wpuf-bg-gray-100 wpuf-text-gray-800': form.post_status === 'draft'
                    }"
                    class="wpuf-inline-flex wpuf-items-center wpuf-px-2.5 wpuf-py-0.5 wpuf-rounded-full wpuf-text-xs wpuf-font-medium">
                    {{ form.post_status === 'publish' ? 'Published' :
                       form.post_status === 'pending' ? 'Pending Review' :
                       form.post_status === 'private' ? 'Private' : 'Draft' }}
                  </span>
                </td>
                <td class="wpuf-whitespace-nowrap wpuf-px-3 wpuf-py-4 wpuf-text-sm wpuf-text-gray-500">
                  <div class="wpuf-flex wpuf-items-center">
                    <code class="wpuf-mr-2">[wpuf_form id="{{ form.ID }}"]</code>
                    <button
                      @click="copyToClipboard(form.ID, $event)"
                      class="wpuf-text-gray-500 hover:wpuf-text-gray-700 wpuf-focus:outline-none"
                      title="Copy shortcode">
                      <svg xmlns="http://www.w3.org/2000/svg" class="wpuf-h-4 wpuf-w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 5H6a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2v-1M8 5a2 2 0 002 2h2a2 2 0 002-2M8 5a2 2 0 012-2h2a2 2 0 012 2m0 0h2a2 2 0 012 2v3m2 4H10m0 0l3-3m-3 3l3 3" />
                      </svg>
                    </button>
                  </div>
                </td>
                <td class="wpuf-whitespace-nowrap wpuf-px-3 wpuf-py-4 wpuf-text-sm wpuf-text-gray-500">
                  <svg
                      v-if="form.settings_guest_post"
                      xmlns="http://www.w3.org/2000/svg"
                      viewBox="0 0 16 16"
                      class="wpuf-size-4 wpuf-w-6">
                    <path fill="#059669" fill-rule="evenodd" d="M12.416 3.376a.75.75 0 0 1 .208 1.04l-5 7.5a.75.75 0 0 1-1.154.114l-3-3a.75.75 0 0 1 1.06-1.06l2.353 2.353 4.493-6.74a.75.75 0 0 1 1.04-.207Z" clip-rule="evenodd" />
                  </svg>
                  <svg
                      v-else
                      xmlns="http://www.w3.org/2000/svg"
                      viewBox="0 0 16 16"
                      class="wpuf-size-4 wpuf-w-6">
                    <path fill="#fca5a5" d="M5.28 4.22a.75.75 0 0 0-1.06 1.06L6.94 8l-2.72 2.72a.75.75 0 1 0 1.06 1.06L8 9.06l2.72 2.72a.75.75 0 1 0 1.06-1.06L9.06 8l2.72-2.72a.75.75 0 0 0-1.06-1.06L8 6.94 5.28 4.22Z" />
                  </svg>

                </td>
                <td class="wpuf-whitespace-nowrap wpuf-px-3 wpuf-py-4 wpuf-text-sm wpuf-text-gray-500 wpuf-text-right">
                  <Menu as="div" class="wpuf-relative wpuf-inline-block wpuf-text-left">
                    <div>
                      <MenuButton class="wpuf-inline-flex wpuf-w-full wpuf-justify-center wpuf-rounded-md wpuf-px-2 wpuf-py-2 wpuf-text-sm wpuf-font-medium wpuf-text-gray-700 hover:wpuf-bg-gray-50 focus:wpuf-outline-none focus-visible:wpuf-ring-2 focus-visible:wpuf-ring-white focus-visible:wpuf-ring-opacity-75">
                        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" class="wpuf-h-5 wpuf-w-5 wpuf-text-gray-400 hover:wpuf-text-gray-600">
                           <path d="M5 12H5.01M12 12H12.01M19 12H19.01M6 12C6 12.5523 5.55228 13 5 13C4.44772 13 4 12.5523 4 12C4 11.4477 4.44772 11 5 11C5.55228 11 6 11.4477 6 12ZM13 12C13 12.5523 12.5523 13 12 13C11.4477 13 11 12.5523 11 12C11 11.4477 11.4477 11 12 11C12.5523 11 13 11.4477 13 12ZM20 12C20 12.5523 19.5523 13 19 13C18.4477 13 18 12.5523 18 12C18 11.4477 18.4477 11 19 11C19.5523 11 20 11.4477 20 12Z" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                        </svg>
                      </MenuButton>
                    </div>

                    <transition
                      enter-active-class="wpuf-transition wpuf-duration-100 wpuf-ease-out"
                      enter-from-class="wpuf-transform wpuf-scale-95 wpuf-opacity-0"
                      enter-to-class="wpuf-transform wpuf-scale-100 wpuf-opacity-100"
                      leave-active-class="wpuf-transition wpuf-duration-75 wpuf-ease-in"
                      leave-from-class="wpuf-transform wpuf-scale-100 wpuf-opacity-100"
                      leave-to-class="wpuf-transform wpuf-scale-95 wpuf-opacity-0"
                    >
                      <MenuItems class="wpuf-absolute wpuf-right-0 wpuf-mt-2 wpuf-w-40 wpuf-origin-top-right wpuf-divide-y wpuf-divide-gray-100 wpuf-rounded-md wpuf-bg-white wpuf-shadow-lg wpuf-ring-1 wpuf-ring-black wpuf-ring-opacity-5 focus:wpuf-outline-none wpuf-z-10">
                        <div class="wpuf-px-1 wpuf-py-1">
                          <MenuItem v-for="item in menuItems" :key="item.action" v-slot="{ active }">
                            <button
                              @click="item.action === 'edit' ? handleEdit(form.ID) :
                                      item.action === 'duplicate' ? handleDuplicate(form.ID) :
                                      item.action === 'trash' ? handleTrash(form.ID) :
                                      item.action === 'restore' ? handleRestore(form.ID) :
                                      handleDelete(form.ID)"
                              :class="[
                                active ? item.activeClass : item.class,
                                'wpuf-group wpuf-flex wpuf-w-full wpuf-items-center wpuf-rounded-md wpuf-px-2 wpuf-py-2 wpuf-text-sm',
                              ]"
                            >
                              {{ item.label }}
                            </button>
                          </MenuItem>
                        </div>
                      </MenuItems>
                    </transition>
                  </Menu>
                </td>
              </tr>
            </tbody>
          </table>
        </div>

        <!-- Pagination -->
        <div v-if="totalPages > 1" class="wpuf-flex wpuf-items-center wpuf-justify-center wpuf-px-4 wpuf-py-3 sm:wpuf-px-6 wpuf-border-t wpuf-border-gray-200 wpuf-bg-white">
          <nav class="wpuf-flex wpuf-items-center wpuf-justify-between wpuf-w-full">
            <div>
              <button
                @click="changePage(currentPage - 1)"
                :disabled="currentPage === 1"
                :class="{ 'wpuf-cursor-not-allowed wpuf-opacity-50': currentPage === 1 }"
                class="wpuf-relative wpuf-inline-flex wpuf-items-center wpuf-rounded-md wpuf-border wpuf-border-gray-300 wpuf-bg-white wpuf-px-4 wpuf-py-2 wpuf-text-sm wpuf-font-medium wpuf-text-gray-700 hover:wpuf-bg-gray-50"
              >
                <svg xmlns="http://www.w3.org/2000/svg" class="wpuf-h-5 wpuf-w-5 wpuf-mr-2" viewBox="0 0 20 20" fill="currentColor">
                  <path fill-rule="evenodd" d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z" clip-rule="evenodd" />
                </svg>
                {{ __('Previous', 'wp-user-frontend') }}
              </button>
            </div>

            <div class="wpuf-flex wpuf-items-center">
              <span
                v-for="page in paginationRange"
                :key="page"
                @click="changePage(page)"
                :class="[
                  page === currentPage
                    ? 'wpuf-bg-primary wpuf-text-white'
                    : 'wpuf-bg-white wpuf-text-gray-500 hover:wpuf-bg-gray-50',
                  'wpuf-relative wpuf-inline-flex wpuf-items-center wpuf-px-4 wpuf-py-2 wpuf-text-sm wpuf-font-medium wpuf-cursor-pointer wpuf-mx-1 wpuf-rounded-md wpuf-border wpuf-border-gray-300'
                ]"
              >
                {{ page }}
              </span>
            </div>

            <div>
              <button
                @click="changePage(currentPage + 1)"
                :disabled="currentPage === totalPages"
                :class="{ 'wpuf-cursor-not-allowed wpuf-opacity-50': currentPage === totalPages }"
                class="wpuf-relative wpuf-inline-flex wpuf-items-center wpuf-rounded-md wpuf-border wpuf-border-gray-300 wpuf-bg-white wpuf-px-4 wpuf-py-2 wpuf-text-sm wpuf-font-medium wpuf-text-gray-700 hover:wpuf-bg-gray-50"
              >
                {{ __('Next', 'wp-user-frontend') }}
                <svg xmlns="http://www.w3.org/2000/svg" class="wpuf-h-5 wpuf-w-5 wpuf-ml-2" viewBox="0 0 20 20" fill="currentColor">
                  <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd" />
                </svg>
              </button>
            </div>
          </nav>
        </div>
      </div>
    </div>
  </div>
</template>

// admin/forms-list/src/components/FormsList.jsx
/**
 * FormsList component — main orchestrator for the forms list page.
 *
 * @since WPUF_SINCE
 */
import { useState, useEffect, useCallback, useMemo, useRef } from '@wordpress/element';
import { __ } from '@wordpress/i18n';
import { applyFilters } from '@wordpress/hooks';

import useFormsFetch from '../hooks/useFormsFetch';
import useClipboard from '../hooks/useClipboard';

import StatusTabs from './StatusTabs';
import SearchBar from './SearchBar';
import BulkActions from './BulkActions';
import FormsTable from './FormsTable';
import Pagination from './Pagination';
import EmptyState from './EmptyState';
import AIConfigModal from './AIConfigModal';

const FormsList = ( {
    postType = 'wpuf_forms',
    formType = 'post',
    pageSlug = 'wpuf-post-forms',
    pageTitle = 'Post Forms',
} ) => {
    const filteredPageTitle = applyFilters( 'wpuf.formsList.pageTitle', pageTitle, formType );

    const isPlainPermalink = wpuf_forms_list.is_plain_permalink;
    const permalinkUrl = wpuf_forms_list.permalink_settings_url;
    const aiConfigured = wpuf_forms_list.ai_configured || false;
    const aiSettingsUrl = wpuf_forms_list.ai_settings_url || '';
    const postCounts = wpuf_forms_list.post_counts;

    const newFormUrl = window.wpuf_admin_script.admin_url + 'admin.php?page=wpuf-' + formType + '-forms&action=add-new';

    const { forms, loading, pagination, fetchForms } = useFormsFetch( { postType } );
    const { copiedKey, copyToClipboard } = useClipboard();

    const [ currentTab, setCurrentTab ] = useState( 'any' );
    const [ searchTerm, setSearchTerm ] = useState( '' );
    const [ selectedForms, setSelectedForms ] = useState( [] );
    const [ selectAllChecked, setSelectAllChecked ] = useState( false );
    const [ selectedBulkAction, setSelectedBulkAction ] = useState( '' );
    const [ showAIConfigModal, setShowAIConfigModal ] = useState( false );

    const debounceTimerRef = useRef( null );
    const isInitialMount = useRef( true );

    // Initial fetch
    useEffect( () => {
        fetchForms( 1, currentTab, searchTerm );
    }, [] );

    // Re-fetch when tab changes (skip initial mount)
    useEffect( () => {
        if ( isInitialMount.current ) {
            isInitialMount.current = false;
            return;
        }
        fetchForms( 1, currentTab, searchTerm );
    }, [ currentTab ] );

    // Debounced search
    const handleSearchChange = useCallback( ( value ) => {
        setSearchTerm( value );

        if ( debounceTimerRef.current ) {
            clearTimeout( debounceTimerRef.current );
        }

        debounceTimerRef.current = setTimeout( () => {
            fetchForms( 1, currentTab, value );
        }, 500 );
    }, [ currentTab, fetchForms ] );

    // Cleanup debounce timer on unmount
    useEffect( () => {
        return () => {
            if ( debounceTimerRef.current ) {
                clearTimeout( debounceTimerRef.current );
            }
        };
    }, [] );

    // Sync selectAllChecked with individual selections
    useEffect( () => {
        if ( forms.length > 0 && selectedForms.length === forms.length ) {
            setSelectAllChecked( true );
        } else {
            setSelectAllChecked( false );
        }
    }, [ selectedForms, forms ] );

    // Reset selections when forms change
    useEffect( () => {
        setSelectedForms( [] );
        setSelectAllChecked( false );
    }, [ forms ] );

    const handleSelectAll = useCallback( () => {
        if ( ! selectAllChecked ) {
            setSelectedForms( forms.map( ( form ) => form.ID ) );
        } else {
            setSelectedForms( [] );
        }
    }, [ selectAllChecked, forms ] );

    const handleSelectForm = useCallback( ( formId ) => {
        setSelectedForms( ( prev ) => {
            if ( prev.includes( formId ) ) {
                return prev.filter( ( id ) => id !== formId );
            }
            return [ ...prev, formId ];
        } );
    }, [] );

    const handleTabChange = useCallback( ( tab ) => {
        setCurrentTab( tab );
    }, [] );

    const handlePageChange = useCallback( ( page ) => {
        fetchForms( page, currentTab, searchTerm );
    }, [ currentTab, searchTerm, fetchForms ] );

    // Build admin URL helper
    const buildAdminUrl = useCallback( ( formId, action ) => {
        const params = new URLSearchParams( {
            page: pageSlug,
            id: formId.toString(),
            action,
        } );

        if ( action !== 'edit' ) {
            params.append( '_wpnonce', wpuf_forms_list.bulk_nonce );
        }

        return `${ window.wpuf_admin_script.admin_url }admin.php?${ params.toString() }`;
    }, [ pageSlug ] );

    // Row action handler
    const handleAction = useCallback( ( action, formId ) => {
        switch ( action ) {
            case 'edit':
                window.location.href = buildAdminUrl( formId, 'edit' );
                break;
            case 'duplicate':
                window.location.href = buildAdminUrl( formId, 'duplicate' );
                break;
            case 'trash':
                window.location.href = buildAdminUrl( formId, 'trash' );
                break;
            case 'restore':
                window.location.href = buildAdminUrl( formId, 'restore' );
                break;
            case 'delete':
                if ( ! window.confirm( __( 'Are you sure you want to delete this form permanently? This action cannot be undone.', 'wp-user-frontend' ) ) ) {
                    return;
                }
                window.location.href = buildAdminUrl( formId, 'delete' );
                break;
        }
    }, [ buildAdminUrl ] );

    // Bulk action handler
    const handleBulkAction = useCallback( () => {
        if ( ! selectedBulkAction || selectedForms.length === 0 ) {
            return;
        }

        const params = new URLSearchParams( {
            page: pageSlug,
            _wpnonce: wpuf_forms_list.bulk_nonce,
            _wp_http_referer: window.location.href,
            action: selectedBulkAction,
            action2: selectedBulkAction,
            bulk_action: 'Apply',
            paged: pagination.current_page.toString(),
        } );

        if ( searchTerm ) {
            params.append( 's', searchTerm );
        }

        if ( currentTab === 'trash' ) {
            params.append( 'post_status', 'trash' );
        }

        selectedForms.forEach( ( formId ) => {
            params.append( 'post[]', formId.toString() );
        } );

        window.location.href = `${ window.wpuf_admin_script.admin_url }admin.php?${ params.toString() }`;
    }, [ selectedBulkAction, selectedForms, pageSlug, searchTerm, currentTab, pagination ] );

    // Open jQuery template modal
    const openModal = useCallback( ( event ) => {
        event.preventDefault();

        if ( window.jQuery ) {
            const $ = window.jQuery;
            const $modal = $( '.wpuf-form-template-modal' );

            $modal.show().removeClass( 'wpuf-hidden' );
            $modal[ 0 ].offsetHeight;

            setTimeout( function () {
                $modal.addClass( 'wpuf-modal-show' );
            }, 10 );

            $( 'body' ).addClass( 'wpuf-modal-open' );
            $( 'body' ).css( 'overflow', 'hidden' );
            $( '#wpbody-content .wrap' ).hide();
        } else {
            window.location.href = newFormUrl;
        }
    }, [ newFormUrl ] );

    // AI Form Builder handler
    const openAIFormBuilder = useCallback( ( event ) => {
        event.preventDefault();

        if ( ! aiConfigured ) {
            setShowAIConfigModal( true );
            return;
        }

        const action = formType === 'profile' ? 'wpuf_profile_form_template' : 'post_form_template';

        const params = new URLSearchParams( {
            action,
            template: 'ai_form',
            _wpnonce: wpuf_forms_list.template_nonce,
        } );

        window.location.href = window.wpuf_admin_script.admin_url + 'admin.php?' + params.toString();
    }, [ aiConfigured, formType ] );

    // Shortcode getter with Pro filter
    const getShortcode = useCallback( ( formId ) => {
        const shortcode = `[wpuf_form id="${ formId }"]`;
        return applyFilters( 'wpuf.formsList.getShortcode', shortcode, formId, formType );
    }, [ formType ] );

    // Copy shortcode handler
    const handleCopyShortcode = useCallback( ( text, key ) => {
        copyToClipboard( text, key );
    }, [ copyToClipboard ] );

    // Menu items based on current tab
    const menuItems = useMemo( () => {
        if ( currentTab === 'trash' ) {
            return [
                {
                    label: __( 'Restore', 'wp-user-frontend' ),
                    action: 'restore',
                    className: '!wpuf-text-gray-900',
                    hoverClassName: 'hover:!wpuf-bg-primary hover:!wpuf-text-white',
                },
                {
                    label: __( 'Delete Permanently', 'wp-user-frontend' ),
                    action: 'delete',
                    className: '!wpuf-text-red-600',
                    hoverClassName: 'hover:!wpuf-bg-red-500 hover:!wpuf-text-white',
                },
            ];
        }

        return [
            {
                label: __( 'Edit', 'wp-user-frontend' ),
                action: 'edit',
                className: '!wpuf-text-gray-900',
                hoverClassName: 'hover:!wpuf-bg-primary hover:!wpuf-text-white',
            },
            {
                label: __( 'Duplicate', 'wp-user-frontend' ),
                action: 'duplicate',
                className: '!wpuf-text-gray-900',
                hoverClassName: 'hover:!wpuf-bg-primary hover:!wpuf-text-white',
            },
            {
                label: __( 'Trash', 'wp-user-frontend' ),
                action: 'trash',
                className: '!wpuf-text-red-600',
                hoverClassName: 'hover:!wpuf-bg-red-500 hover:!wpuf-text-white',
            },
        ];
    }, [ currentTab ] );

    // Determine empty state type
    const getEmptyStateType = () => {
        if ( searchTerm !== '' ) {
            return 'search';
        }
        if ( currentTab === 'any' ) {
            return 'empty';
        }
        return 'tab-empty';
    };

    return (
        <div>
            { /* Permalink Notice */ }
            { isPlainPermalink && (
                <div className="wpuf-bg-yellow-50 wpuf-border wpuf-border-yellow-200 wpuf-rounded-md wpuf-p-4 wpuf-mt-6">
                    <div className="wpuf-flex">
                        <div className="wpuf-flex-shrink-0">
                            <svg className="wpuf-h-5 wpuf-w-5 wpuf-text-yellow-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                                <path fillRule="evenodd" d="M8.485 2.495c.673-1.167 2.357-1.167 3.03 0l6.28 10.875c.673 1.167-.17 2.625-1.516 2.625H3.72c-1.347 0-2.189-1.458-1.515-2.625L8.485 2.495zM10 5a.75.75 0 01.75.75v3.5a.75.75 0 01-1.5 0v-3.5A.75.75 0 0110 5zm0 9a1 1 0 100-2 1 1 0 000 2z" clipRule="evenodd" />
                            </svg>
                        </div>
                        <div className="wpuf-ml-3">
                            <h3 className="wpuf-text-sm wpuf-font-medium wpuf-text-yellow-800">
                                { __( 'WordPress REST API Issue Detected', 'wp-user-frontend' ) }
                            </h3>
                            <div className="wpuf-mt-2 wpuf-text-sm wpuf-text-yellow-700">
                                <p>
                                    { __( 'Your WordPress permalinks are set to "Plain" which may cause issues with fetching the forms. For better functionality, please consider changing your permalink structure.', 'wp-user-frontend' ) }
                                </p>
                            </div>
                            <div className="wpuf-mt-4">
                                <div className="wpuf-flex">
                                    <a
                                        href={ permalinkUrl }
                                        className="wpuf-bg-yellow-50 wpuf-text-yellow-800 wpuf-rounded-md wpuf-border wpuf-border-yellow-300 wpuf-px-3 wpuf-py-2 wpuf-text-sm wpuf-font-medium hover:wpuf-bg-yellow-100 focus:wpuf-outline-none focus:wpuf-ring-2 focus:wpuf-ring-offset-2 focus:wpuf-ring-yellow-500"
                                    >
                                        { __( 'Go to Permalink Settings', 'wp-user-frontend' ) }
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            ) }

            { /* Page title and action buttons */ }
            <div className="wpuf-flex wpuf-justify-between wpuf-items-center wpuf-mt-9">
                <h3 className="wpuf-text-2xl wpuf-font-bold wpuf-m-0 wpuf-p-0 wpuf-leading-none">
                    { filteredPageTitle }
                </h3>
                <div className="wpuf-flex wpuf-gap-3">
                    <button
                        type="button"
                        onClick={ openAIFormBuilder }
                        className="wpuf-rounded-md wpuf-text-center wpuf-bg-gradient-to-r wpuf-from-purple-600 wpuf-to-blue-600 wpuf-px-3 wpuf-py-2 wpuf-text-sm wpuf-font-semibold wpuf-text-white wpuf-shadow-sm hover:wpuf-from-purple-700 hover:wpuf-to-blue-700 hover:wpuf-text-white focus:wpuf-from-purple-700 focus:wpuf-to-blue-700 focus:wpuf-text-white focus:wpuf-shadow-none hover:wpuf-cursor-pointer wpuf-inline-flex wpuf-items-center"
                    >
                        <svg className="wpuf-w-5 wpuf-h-5 wpuf-pr-1" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M8.17766 13.2532L7.5 15.625L6.82234 13.2532C6.4664 12.0074 5.4926 11.0336 4.24682 10.6777L1.875 10L4.24683 9.32234C5.4926 8.9664 6.4664 7.9926 6.82234 6.74682L7.5 4.375L8.17766 6.74683C8.5336 7.9926 9.5074 8.9664 10.7532 9.32234L13.125 10L10.7532 10.6777C9.5074 11.0336 8.5336 12.0074 8.17766 13.2532Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
                            <path d="M15.2157 7.26211L15 8.125L14.7843 7.26212C14.5324 6.25444 13.7456 5.46764 12.7379 5.21572L11.875 5L12.7379 4.78428C13.7456 4.53236 14.5324 3.74556 14.7843 2.73789L15 1.875L15.2157 2.73788C15.4676 3.74556 16.2544 4.53236 17.2621 4.78428L18.125 5L17.2621 5.21572C16.2544 5.46764 15.4676 6.25444 15.2157 7.26211Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
                            <path d="M14.0785 17.1394L13.75 18.125L13.4215 17.1394C13.2348 16.5795 12.7955 16.1402 12.2356 15.9535L11.25 15.625L12.2356 15.2965C12.7955 15.1098 13.2348 14.6705 13.4215 14.1106L13.75 13.125L14.0785 14.1106C14.2652 14.6705 14.7045 15.1098 15.2644 15.2965L16.25 15.625L15.2644 15.9535C14.7045 16.1402 14.2652 16.5795 14.0785 17.1394Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
                        </svg>
                        { __( 'AI Form Builder', 'wp-user-frontend' ) }
                    </button>
                    <button
                        type="button"
                        onClick={ openModal }
                        className="new-wpuf-form wpuf-rounded-md wpuf-text-center wpuf-bg-primary wpuf-px-3 wpuf-py-2 wpuf-text-sm wpuf-font-semibold wpuf-text-white wpuf-shadow-sm hover:wpuf-bg-primaryHover hover:wpuf-text-white focus:wpuf-bg-primaryHover focus:wpuf-text-white focus:wpuf-shadow-none hover:wpuf-cursor-pointer"
                    >
                        <span className="dashicons dashicons-plus-alt2"></span>
                        &nbsp;
                        { __( 'Add New ', 'wp-user-frontend' ) }
                    </button>
                </div>
            </div>

            { /* Status Tabs */ }
            <StatusTabs
                postCounts={ postCounts }
                currentTab={ currentTab }
                onTabChange={ handleTabChange }
            />

            { /* Bulk Actions & Search */ }
            <div className="wpuf-flex wpuf-justify-between wpuf-my-8">
                <BulkActions
                    currentTab={ currentTab }
                    selectedBulkAction={ selectedBulkAction }
                    onBulkActionChange={ setSelectedBulkAction }
                    onApply={ handleBulkAction }
                    disabled={ selectedForms.length === 0 }
                />
                <SearchBar
                    value={ searchTerm }
                    onChange={ handleSearchChange }
                />
            </div>

            { /* Loading State — matches Vue HollowDotsSpinner */ }
            { loading && (
                <>
                    <style>{ `
                        @keyframes hollow-dots-spinner-animation {
                            50% { transform: scale(1); opacity: 1; }
                            100% { opacity: 0; }
                        }
                        .wpuf-hollow-dots-spinner {
                            display: flex;
                            gap: 15px;
                        }
                        .wpuf-hollow-dots-spinner .wpuf-dot {
                            width: 20px;
                            height: 20px;
                            border: 3px solid #7DC442;
                            border-radius: 50%;
                            transform: scale(0);
                            animation: hollow-dots-spinner-animation 1s ease infinite 0ms;
                        }
                    ` }</style>
                    <div className="wpuf-flex wpuf-h-16 wpuf-items-center wpuf-justify-center">
                        <div className="wpuf-hollow-dots-spinner">
                            <div className="wpuf-dot" style={ { animationDelay: '0.3s' } }></div>
                            <div className="wpuf-dot" style={ { animationDelay: '0.6s' } }></div>
                            <div className="wpuf-dot" style={ { animationDelay: '0.9s' } }></div>
                        </div>
                    </div>
                </>
            ) }

            { /* Empty States */ }
            { ! loading && forms.length === 0 && (
                <EmptyState
                    type={ getEmptyStateType() }
                    onAddNew={ openModal }
                    onAIFormBuilder={ openAIFormBuilder }
                />
            ) }

            { /* Forms Table */ }
            { ! loading && forms.length > 0 && (
                <>
                    <FormsTable
                        forms={ forms }
                        currentTab={ currentTab }
                        selectedForms={ selectedForms }
                        selectAllChecked={ selectAllChecked }
                        onSelectAll={ handleSelectAll }
                        onSelectForm={ handleSelectForm }
                        onAction={ handleAction }
                        postType={ postType }
                        getShortcode={ getShortcode }
                        copiedKey={ copiedKey }
                        onCopyShortcode={ handleCopyShortcode }
                        menuItems={ menuItems }
                    />

                    <Pagination
                        currentPage={ pagination.current_page }
                        totalPages={ pagination.total_pages }
                        onPageChange={ handlePageChange }
                    />
                </>
            ) }

            { /* AI Config Modal */ }
            <AIConfigModal
                isOpen={ showAIConfigModal }
                onClose={ () => setShowAIConfigModal( false ) }
                onGoToSettings={ () => { window.location.href = aiSettingsUrl; } }
            />
        </div>
    );
};

export default FormsList;
